import type { ScamPattern } from '@/lib/types';

export const SCAM_PATTERNS: ScamPattern[] = [
  {
    id: 'phishing',
    title: 'Phishing (Link Palsu)',
    description: 'Penipu mengirim link palsu yang menyerupai situs resmi bank, e-commerce, atau layanan pemerintah untuk mencuri data login dan informasi pribadi Anda.',
    icon: '🎣',
    riskLevel: 'berbahaya',
    examples: [
      'Link "verifikasi akun BCA" yang mengarah ke situs palsu',
      'Email dari "Shopee" meminta update data kartu kredit',
      'SMS berisi link tracking paket palsu',
    ],
    howToProtect: [
      'Jangan pernah klik link dari sumber yang tidak dikenal',
      'Periksa URL dengan teliti — situs resmi menggunakan domain resmi (bca.co.id, bukan bca-verify.com)',
      'Bank tidak pernah meminta PIN atau OTP melalui link',
      'Jika ragu, buka aplikasi resmi bank langsung',
    ],
    indicators: [
      'URL yang tidak sesuai dengan situs resmi',
      'Permintaan data sensitif (password, OTP, PIN)',
      'Bahasa yang mendesak dan menakutkan',
      'Tampilan halaman yang sedikit berbeda dari aslinya',
    ],
  },
  {
    id: 'qris-scam',
    title: 'Penipuan QRIS',
    description: 'Penipu memanipulasi kode QRIS di tempat-tempat umum seperti masjid, toko, atau warung dengan menempelkan QRIS palsu yang mengarah ke rekening mereka.',
    icon: '📱',
    riskLevel: 'berbahaya',
    examples: [
      'QRIS palsu ditempel di atas QRIS asli kotak amal masjid',
      'Penipu mengirim QRIS pembayaran palsu via WhatsApp',
      'Struk pembayaran QRIS yang diedit/palsu',
    ],
    howToProtect: [
      'Pastikan nama penerima di QRIS sesuai dengan nama toko/institusi',
      'Jangan scan QRIS dari sumber yang tidak terpercaya',
      'Periksa apakah stiker QRIS tidak ditempeli stiker lain',
      'Konfirmasi pembayaran langsung ke penjual',
    ],
    indicators: [
      'Nama penerima tidak sesuai',
      'QRIS yang dikirim via chat/pesan',
      'Stiker QRIS yang terlihat ditempel ulang',
      'Diminta membayar ke QRIS pribadi, bukan bisnis',
    ],
  },
  {
    id: 'fake-job',
    title: 'Lowongan Kerja Palsu',
    description: 'Penipu menawarkan pekerjaan dengan gaji fantastis dan syarat mudah, tetapi meminta korban membayar "biaya aktivasi" atau "modal awal" terlebih dahulu.',
    icon: '💼',
    riskLevel: 'berbahaya',
    examples: [
      'Kerja online like & subscribe YouTube, gaji Rp 500rb-2jt/hari',
      'Lowongan data entry dari rumah, gaji Rp 15jt/bulan, minta bayar aktivasi Rp 100rb',
      'Tawaran jadi reseller tanpa modal tapi minta transfer "biaya admin"',
    ],
    howToProtect: [
      'Pekerjaan asli tidak pernah minta bayar di awal',
      'Gaji yang terlalu tinggi untuk pekerjaan mudah = red flag',
      'Cek perusahaan di Google dan situs resmi',
      'Jangan transfer uang untuk "biaya aktivasi" atau "modal awal"',
    ],
    indicators: [
      'Gaji tidak realistis',
      'Minta transfer uang di awal',
      'Tidak ada info perusahaan yang jelas',
      'Rekrutmen via WhatsApp/Telegram tanpa proses formal',
    ],
  },
  {
    id: 'fake-cs',
    title: 'Customer Service Palsu',
    description: 'Penipu berpura-pura menjadi customer service bank, e-commerce, atau layanan digital untuk mendapatkan data pribadi dan akses ke akun atau rekening Anda.',
    icon: '🎧',
    riskLevel: 'berbahaya',
    examples: [
      'Telepon dari "Bank BCA" yang meminta verifikasi data karena ada transaksi mencurigakan',
      'Chat WhatsApp dari "CS Shopee" yang meminta data login',
      'DM Instagram dari "admin marketplace" tentang masalah pesanan',
    ],
    howToProtect: [
      'CS bank tidak pernah meminta PIN, OTP, atau password',
      'Hubungi CS resmi melalui nomor/channel yang tertera di situs resmi',
      'Jangan berikan kode OTP kepada siapapun',
      'Bank tidak pernah menelepon untuk meminta data sensitif',
    ],
    indicators: [
      'Meminta OTP, PIN, atau password',
      'Nomor telepon/WA bukan nomor resmi',
      'Mendesak untuk bertindak segera',
      'Mengancam akan memblokir akun',
    ],
  },
  {
    id: 'whatsapp-scam',
    title: 'Penipuan WhatsApp',
    description: 'Berbagai jenis penipuan yang disebarkan melalui WhatsApp, termasuk undian palsu, hadiah gratis, dan pesan berantai yang berisi link berbahaya.',
    icon: '📲',
    riskLevel: 'mencurigakan',
    examples: [
      '"Selamat! Anda memenangkan undian Telkomsel Rp 50 juta"',
      'Pesan dari "teman" yang minta pinjaman uang (akun diretas)',
      'Undangan pernikahan digital berisi APK malware',
    ],
    howToProtect: [
      'Tidak ada undian resmi yang meminta data via WhatsApp',
      'Jangan install file APK dari WhatsApp',
      'Jika teman minta pinjaman, konfirmasi via telepon langsung',
      'Jangan forward pesan berantai yang berisi link',
    ],
    indicators: [
      'Hadiah/undian yang tidak pernah diikuti',
      'File APK atau link yang dikirim via WA',
      'Permintaan transfer uang yang mendesak',
      'Pesan dari nomor tidak dikenal mengaku kenal',
    ],
  },
  {
    id: 'otp-scam',
    title: 'Penipuan OTP',
    description: 'Penipu mencoba mendapatkan kode OTP (One-Time Password) Anda untuk mengakses akun bank, e-wallet, atau layanan digital Anda.',
    icon: '🔐',
    riskLevel: 'berbahaya',
    examples: [
      '"Maaf salah kirim kode, bisa tolong forward kode yang masuk ke HP Anda?"',
      'Telepon mengaku dari bank meminta kode verifikasi',
      'SMS palsu seolah dari bank meminta balas kode OTP',
    ],
    howToProtect: [
      'JANGAN PERNAH berikan kode OTP kepada siapapun',
      'OTP hanya untuk Anda — bahkan bank tidak boleh memintanya',
      'Jika ada yang minta OTP, itu pasti penipuan',
      'Aktifkan autentikasi 2 faktor di semua akun penting',
    ],
    indicators: [
      'Siapapun yang meminta kode OTP',
      'Alasan "salah kirim" atau "verifikasi"',
      'Tekanan untuk segera mengirim kode',
      'Mengaku sebagai pihak resmi',
    ],
  },
  {
    id: 'investment-scam',
    title: 'Penipuan Investasi',
    description: 'Tawaran investasi dengan keuntungan besar dalam waktu singkat. Biasanya menggunakan skema Ponzi atau binary options palsu.',
    icon: '📈',
    riskLevel: 'berbahaya',
    examples: [
      'Trading binary option dengan "profit pasti 50% per bulan"',
      'Investasi crypto dengan "jaminan profit" dari mentor/guru',
      'Arisan online dengan keuntungan berlipat ganda',
    ],
    howToProtect: [
      'Tidak ada investasi yang menjamin keuntungan pasti',
      'Cek legalitas di OJK (Otoritas Jasa Keuangan)',
      'Keuntungan besar = risiko besar atau penipuan',
      'Jangan invest uang yang Anda tidak siap kehilangan',
    ],
    indicators: [
      'Janji keuntungan pasti dan besar',
      'Tidak terdaftar di OJK',
      'Minta rekrut member baru',
      'Testimonial palsu dan screenshot profit yang diedit',
    ],
  },
  {
    id: 'social-engineering',
    title: 'Social Engineering',
    description: 'Teknik manipulasi psikologis untuk mendapatkan informasi atau akses. Penipu memanfaatkan emosi, rasa percaya, dan ketidaktahuan korban.',
    icon: '🧠',
    riskLevel: 'mencurigakan',
    examples: [
      'Mengaku sebagai teman lama yang butuh bantuan darurat',
      'Berpura-pura sebagai kurir yang minta konfirmasi alamat + data pribadi',
      'Email dari "bos" yang minta transfer mendesak (Business Email Compromise)',
    ],
    howToProtect: [
      'Selalu verifikasi identitas orang yang menghubungi Anda',
      'Jangan terburu-buru mengambil keputusan karena tekanan',
      'Jika ragu, konfirmasi melalui channel komunikasi lain',
      'Jangan bagikan informasi pribadi ke orang yang tidak dikenal',
    ],
    indicators: [
      'Membuat Anda merasa terburu-buru atau panik',
      'Cerita yang menyentuh emosi (sakit, kecelakaan, dll)',
      'Meminta bantuan finansial mendesak',
      'Informasi personal yang seharusnya rahasia diminta secara casual',
    ],
  },
];
